<?php
/**
 * Plugin Name: LGL Shortcodes
 * Plugin URI: https://digitallydisruptive.co.uk/
 * Description: A robust, OOP-based plugin to output customized data via shortcodes using a dynamic template routing system.
 * Version: 1.1.0
 * Author: Digitally Disruptive - Donald Raymundo
 * Author URI: https://digitallydisruptive.co.uk/
 * Text Domain: lgl-shortcodes
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Prevent direct access to the file.
}

// Define a constant for the plugin directory path to ensure reliable file inclusion.
define( 'LGL_SHORTCODES_PATH', plugin_dir_path( __FILE__ ) );

if ( ! class_exists( 'LGL_Shortcodes' ) ) {

    /**
     * Main class for the LGL Shortcodes plugin.
     * Manages the registration, parameter parsing, and template routing of all shortcodes.
     */
    class LGL_Shortcodes {

        /**
         * Initializes the plugin by hooking into the WordPress lifecycle.
         *
         * @return void
         */
        public function __construct() {
            add_action( 'init', array( $this, 'register_shortcodes' ) );
        }

        /**
         * Registers the defined shortcodes with the WordPress Shortcode API.
         * Routes callbacks to a unified template rendering method.
         *
         * @return void
         */
        public function register_shortcodes() {
            // Registering the original shortcode and the new search shortcode
            add_shortcode( 'lgl_data', array( $this, 'render_shortcode' ) );
            add_shortcode( 'lgl_search', array( $this, 'render_shortcode' ) );
        }

        /**
         * A unified callback function that processes shortcodes and routes them to external template files.
         * Uses the shortcode tag to determine the required template name dynamically.
         *
         * @param array  $atts          The array of attributes passed by the user.
         * @param string $content       The enclosed content between opening and closing shortcode tags, if any.
         * @param string $shortcode_tag The name of the shortcode tag currently being executed.
         * @return string The sanitized and formatted HTML string generated by the required template.
         */
        public function render_shortcode( $atts, $content = null, $shortcode_tag = '' ) {
            // Normalize the shortcode tag to match file naming conventions (e.g., 'lgl_search' becomes 'lgl-search')
            $template_name = str_replace( '_', '-', $shortcode_tag );

            // Ensure attributes are treated as an array to prevent type errors during extraction
            $attributes = (array) $atts;

            // Hand over execution to the template loader
            return $this->load_template( $template_name, $attributes, $content );
        }

        /**
         * Locates, isolates variables, and loads the requested template file.
         * Prioritizes theme overrides before falling back to the default plugin template.
         *
         * @param string $template_name The base name of the template file (without extension).
         * @param array  $attributes    The associative array of shortcode attributes.
         * @param string $content       The enclosed shortcode content.
         * @return string The buffered HTML content rendered by the template.
         */
        private function load_template( $template_name, $attributes, $content ) {
            // 1. Define the default template path inside the plugin's /templates directory
            $plugin_path = LGL_SHORTCODES_PATH . 'templates/' . $template_name . '.php';

            // 2. Check if the active theme contains an override file (e.g., your-theme/lgl-shortcodes/lgl-search.php)
            $theme_override = locate_template( 'lgl-shortcodes/' . $template_name . '.php' );

            // 3. Select the correct file path prioritizing the theme override
            $file_to_load = ( $theme_override ) ? $theme_override : $plugin_path;

            // 4. Return an HTML comment for debugging if the template does not exist
            if ( ! file_exists( $file_to_load ) ) {
                return '';
            }

            // 5. Extract attributes into individual variables for cleaner usage within the template file
            // EXTR_SKIP prevents existing variables in this method's scope from being accidentally overwritten
            extract( $attributes, EXTR_SKIP );

            // 6. Initialize output buffering to safely capture the included file's output
            ob_start();
            include $file_to_load;
            return ob_get_clean();
        }
    }

    // Instantiate the plugin architecture
    new LGL_Shortcodes();
}